### ISSUE TITLE
Integration of buridan-ui with Django

### ISSUE THREAD

**Issue by SBIA-Younes** [LineIndent/buridan-ui#4]
### **Hello,**

I am interested in using buridan-ui in a Django project, and I would like to know if it is possible to integrate this package with Django.

I have a few questions regarding this:

  1. Are there any examples or guides on how to use `buridan-ui `with Django?
  2. Are there any specific considerations to keep in mind during this integration?
  3.  Do you have any recommendations on the best way to proceed?

Thank you in advance for your help!

Best regards,

**Comment by LineIndent** [comment]
Hi - I'm not sure buridan ui can be integrated with Django as this library is built entirely with Reflex and as a result uses Python for both front and back end. 

If you want to use one of the components with Django, I think the best way to do this would be to extract the props (CSS) from a specific item and build it separately using HTML (which is what Django uses for front end I think). 

But as of now I don't think Reflex apps can be integrated with Django
